
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfvqxakrryltsavukpsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdnF4YWtycnlsdHNhdnVrcHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODk2MTYsImV4cCI6MjA1OTk2NTYxNn0.q_sXtUlR5uOy-S8UnELYogUnCDZSFPDKDtIZz66EcbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase-auth'
  }
});
